# Generated by Django 3.2.4 on 2021-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210614_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.TextField(default='<p class="block text-block"></p>'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='New Page', max_length=200),
        ),
    ]
