# Generated by Django 3.2.4 on 2021-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pages', '0004_auto_20210614_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='viewers',
            field=models.ManyToManyField(related_name='viewable_pages', to='accounts.Profile'),
        ),
    ]
